{
 "title": "Data Factory Test",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "status", "label": "status", "query": { "query": "conductor_server_tasks_total" } },
   {
    "name": "taskType",
    "label": "Task",
    "query": {
     "query": "query_result(task_execution_total)"
    }
   },
   {
    "name": "workflowType",
    "label": "workflow",
    "query": {
     "query": "conductor_server_workflows_execution_time_avg"
    }
   },
   {
    "name": "instance",
    "label": "Prometheus instance",
    "query": {
     "query": "jvm_threads_live_threads{app_kubernetes_io_name=\"yuba-saronite-cd\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Applicatif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "YubaLog - events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "delta(app_event_consumed_total[2m]) ",
       "legendFormat": "{{ event_emitter_name }} - {{ event_code}}"
      }
     ]
    },
    {
     "title": "Taux moyen d'item importé par seconde par compte",
     "type": "timeseries",
     "description": "Le calcul prend en compte l'ensemble des worker (taux sur l'ensemble des worker)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by (account_id) (rate(app_item_imported_total[2m]))",
       "legendFormat": "{{account_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Workflow & Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Tasks Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(task_queue_wait_total{kubernetes_pod_name=\"$instance\", taskType=~\"$taskType\"}[2m]) > 0",
     "legendFormat": "{{taskType}}"
    }
   ]
  },
  {
   "title": "Nombre de tache en Erreur",
   "type": "timeseries",
   "description": "Nombre de tache dans le FAILED ou TIME_OUT",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(task_execution_total{kubernetes_pod_name=\"$instance\", taskType=~\"$taskType\", status=~'(FAILED)|(TIME_OUT)'}[2m]) > 0",
     "legendFormat": "{{taskType}}-{{status}}"
    }
   ]
  },
  {
   "title": "Workflows average execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "workflow_execution_seconds_sum{kubernetes_pod_name=\"$instance\"}\n",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflow Types running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(workflow_running) by (workflowName) > 0",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Conductor Decision Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "workflow_decision_seconds_max{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "workflow_decision_seconds"
    }
   ]
  },
  {
   "title": "Tasks Queue Unacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (task_queue_depth{kubernetes_pod_name=\"$instance\"}) by (taskType) > 0",
     "legendFormat": "{{taskType}}"
    }
   ]
  },
  {
   "title": "Temps moyen d'attente des TACHES : $taskType",
   "type": "timeseries",
   "description": "Temps moyen d'attente d'une tache avant qu'elle sois récupérée par un worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(task_queue_wait_seconds_sum{kubernetes_pod_name=\"$instance\", taskType=~\"$taskType\"}[1m])",
     "legendFormat": "{{taskType}}"
    }
   ]
  }
 ]
}